name             'learn_chef_httpd'
maintainer       'Learn Chef'
maintainer_email 'learnchef@getchef.com'
license          'Apache 2.0'
description      'Installs and configures package httpd and sets a basic home page.'
long_description 'Installs and configures package httpd and sets a basic home page. This cookbook is used by the Learn Chef tutorials. http://learn.getchef.com'
supports         'centos'
supports         'redhat'
version          '0.1.0'
